---
title: "DATA 2010 Group Project"
author: "Lucas Berzuk, Ethan Robson, Hugo Ng, Rodell Salonga"
date: "Due on 015/03/2024"
output: pdf_document
header-includes:
  - \linespread{1.3}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=90), tidy=TRUE)
```

```{r}
# This will be the RMD file that we use for all of our work

# Adding thias from hugos computer to see if this works
# trying to commit

# Test thhsihsuhsug
# Rodell test
# Hugo second test 
```

```{r}
# No one touch this
library (readr)
urlfile = "https://github.com/LucasBerzuk/DATA2010Project/blob/main/ObesityDataSet_raw_and_data_sinthetic.csv"
ObesityDataset = ObesityDataSet_raw_and_data_sinthetic
ObesityDataset
```

```{r}
# Descriptive analysis
# Background information 
# Where it cam from what its telling us what its trying to achieve/show
```

```{r}
# Current status
# What have we done to the data (exploratory analysis) 
# What we found etc
```

```{r}
# Future direction
# What do we wanna do/goal
```